#ifndef MASTER_FLAT_TABLE_H
#define MASTER_FLAT_TABLE_H

#include "../abe_schemes/cpabe_switcher.h"

enum bfm_type {
    /**
     * The Quine-McCluskey algorithm, which is an optimal BFM algorithm.
     */
    QUINE_MC_CLUSKEY,
    /**
     * The Espresso logic minimizer, which is an approximation algorithm for BFM.
     */
    ESPRESSO
};

/**
 * Tests the functionality of the Flat Table ABE SGC scheme with a specific Boolean Function Minimization (BFM)
 * algorithm and a specific CP-ABE scheme and prints the result.
 * @param[in] size the group size.
 * @param[in] bfm_type the chosen Boolean Function Minimization (BFM) algorithm.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void flat_table_test(int size, bfm_type bfm_type, cpabe_switcher::abe_type cpabe_type);

/**
 * Measures and prints the average runtimes and standard deviation for the join and leave operations on the group
 * controller.
 * @param[in] size the group size.
 * @param[in] precision how many digits to print after the decimal point of the runtimes.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] bfm_type the chosen Boolean Function Minimization (BFM) algorithm.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void flat_table_run_gc(int size, int precision, int repetitions, bfm_type bfm_type, cpabe_switcher::abe_type cpabe_type);

/**
 * Generates and saves update the key update messages for the group members for the measurements on the group members.
 * @param[in] file_prefix file prefix for saving the files to the filesystem. The full file names are
 *      <file_prefix><counter>.bin
 * @param[in] join_ind_key the individual key that only the joining user and the group controller share.
 * @param[in] size the group size.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] bfm_type the chosen Boolean Function Minimization (BFM) algorithm.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void flat_table_generate_messages(const std::string& file_prefix, const std::vector<unsigned char>& join_ind_key,
                              int size, int repetitions, bfm_type bfm_type, cpabe_switcher::abe_type cpabe_type);

/**
 * Measures and prints the average runtimes and standard deviation for the join and leave operations on a group member.
 * It loads the update messages from the filesystem.
 * @param[in] file_prefix file prefix for loading the files from the disk. The full file names are
 *      <file_prefix><counter>.bin
 * @param[in] join_ind_key the individual key that only the joining user and the group controller share.
 * @param[in] precision how many digits to print after the decimal point of the runtimes.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] bfm_type the chosen Boolean Function Minimization (BFM) algorithm.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void flat_table_run_gm(const std::string& file_prefix, const std::vector<unsigned char>& join_ind_key, int precision,
                   int repetitions, bfm_type bfm_type, cpabe_switcher::abe_type cpabe_type);

/**
 * Measures and prints the sizes of the key update messages generated by the group controller for joining and leaving
 * the group.
 * @param[in] size the group size.
 * @param[in] bfm_type the chosen Boolean Function Minimization (BFM) algorithm.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void flat_table_measure_byte_lengths(int size, bfm_type bfm_type, cpabe_switcher::abe_type cpabe_type);

#endif //MASTER_FLAT_TABLE_H
