#ifndef MASTER_NAIVE_CPABE_H
#define MASTER_NAIVE_CPABE_H

#include "../abe_schemes/cpabe_switcher.h"

/**
 * Tests the functionality of the Naive CP-ABE SGC scheme with a specific CP-ABE scheme and prints the result.
 * @param[in] size the group size.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void naive_cpabe_test(int size, cpabe_switcher::abe_type cpabe_type);

/**
 * Measures and prints the average runtimes and standard deviation for the join and leave operations on the group
 * controller.
 * @param[in] size the group size.
 * @param[in] precision how many digits to print after the decimal point of the runtimes.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void naive_cpabe_run_gc(int size, int precision, int repetitions, cpabe_switcher::abe_type cpabe_type);

/**
 * Generates and saves update the key update messages for the group members for the measurements on the group members.
 * @param[in] file_prefix file prefix for saving the files to the filesystem. The full file names are
 *      <file_prefix><counter>.bin
 * @param[in] join_ind_key the individual key that only the joining user and the group controller share.
 * @param[in] size the group size.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void naive_cpabe_generate_messages(const std::string& file_prefix, const std::vector<unsigned char>& join_ind_key,
                                   int size, int repetitions, cpabe_switcher::abe_type cpabe_type);

/**
 * Measures and prints the average runtimes and standard deviation for the join and leave operations on a group member.
 * It loads the update messages from the filesystem.
 * @param[in] file_prefix file prefix for loading the files from the disk. The full file names are
 *      <file_prefix><counter>.bin
 * @param[in] join_ind_key the individual key that only the joining user and the group controller share.
 * @param[in] precision how many digits to print after the decimal point of the runtimes.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void naive_cpabe_run_gm(const std::string& file_prefix, const std::vector<unsigned char>& join_ind_key,
                        int precision, int repetitions, cpabe_switcher::abe_type cpabe_type);

/**
 * Measures and prints the sizes of the key update messages generated by the group controller for joining and leaving
 * the group.
 * @param[in] size the group size.
 * @param[in] cpabe_type the chosen CP-ABE scheme.
 */
void naive_cpabe_measure_byte_lengths(int size, cpabe_switcher::abe_type cpabe_type);

#endif //MASTER_NAIVE_CPABE_H
