#ifndef MASTER_LKH_H
#define MASTER_LKH_H

#include <vector>
#include <string>

/**
 * Tests the functionality of the LKH SGC scheme and prints the result.
 * @param[in] size the group size.
 * @param[in] degree the degree of the KeyTree.
 * @param[in] print_tree whether to print the KeyTree in between single tests.
 * @param[in] use_kor whether to use Key-Oriented Re-keying (KOR) or User-Oriented Re-keying (UOR).
 * @see KeyTree
 */
void lkh_test(int size, int degree, bool print_tree, int use_kor);

/**
 * Measures and prints the average runtimes and standard deviation for the join and leave operations on the group
 * controller.
 * @param[in] size the group size.
 * @param[in] degree the degree of the KeyTree.
 * @param[in] precision how many digits to print after the decimal point of the runtimes.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] use_kor whether to use Key-Oriented Re-keying (KOR) or User-Oriented Re-keying (UOR).
 * @see KeyTree
 */
void lkh_run_gc(int size, int degree, int precision, int repetitions, int use_kor);

/**
 * Generates and saves update the key update messages for the group members for the measurements on the group members.
 * @param[in] file_prefix file prefix for saving the files to the filesystem. The full file names are
 *      <file_prefix><counter>.bin
 * @param[in] join_ind_key the individual key that only the joining user and the group controller share.
 * @param[in] size the group size.
 * @param[in] degree the degree of the KeyTree.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] use_kor whether to use Key-Oriented Re-keying (KOR) or User-Oriented Re-keying (UOR).
 * @see KeyTree
 */
void lkh_generate_messages(const std::string& file_prefix, const std::vector<unsigned char>& join_ind_key,
                           int size, int degree, int repetitions, int use_kor);

/**
 * Measures and prints the average runtimes and standard deviation for the join and leave operations on a group member.
 * It loads the update messages from the filesystem.
 * @param[in] file_prefix file prefix for loading the files from the disk. The full file names are
 *      <file_prefix><counter>.bin
 * @param[in] join_ind_key the individual key that only the joining user and the group controller share.
 * @param[in] precision how many digits to print after the decimal point of the runtimes.
 * @param[in] repetitions how many repetitions to perform for each measurement.
 * @param[in] use_kor whether to use Key-Oriented Re-keying (KOR) or User-Oriented Re-keying (UOR).
 */
void lkh_run_gm(const std::string& file_prefix, const std::vector<unsigned char>& join_ind_key, int precision,
                int repetitions, int use_kor);

/**
 * Measures and prints the sizes of the key update messages generated by the group controller for joining and leaving
 * the group.
 * @param[in] size the group size.
 * @param[in] degree the degree of the KeyTree.
 * @param[in] use_kor whether to use Key-Oriented Re-keying (KOR) or User-Oriented Re-keying (UOR).
 * @see KeyTree
 */
void lkh_measure_byte_lengths(int size, int degree, int use_kor);

#endif //MASTER_LKH_H
